before_script:
  - apt-get update -q
  - apt-get install -y clang valgrind cmake python2.7 libboost-regex-dev libboost-dev 
  - ./build-libmarpa.sh
  - cd tests; cat cli/* ep/* simple/* slower/* > t; cd ..

#- ./perms.py > perms.cpp

make_with_marpa:
  script:
    - make clean
    - ASAN="" make -e with_marpa  
    - "LD_PRELOAD=libmarpa/dist/.libs/libmarpa.so valgrind ./tau  --silence addrules --silence readcurly --silence quad::ctor --silence N3  < tests/t | grep test:"

cmake_m-tau:
  script:
    - mkdir build; cd build; cmake ..; make m-tau ; cd ..
    - LD_PRELOAD=libmarpa/dist/.libs/libmarpa.so build/m-tau   --silence addrules --silence readcurly --silence quad::ctor --silence N3    < tests/t

#cmake_tau:
#  script:
#    - mkdir build; cd build; cmake ..; make tau 
#    - ./tau < tests/simple/1

release:
  script:
    - make clean
    - ./r
    - valgrind ./tau  < tests/slower/einstein.n3
    - time ./tau  < tests/slower/einstein.n3
