language: cpp

compiler:
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev

install: ./build-libmarpa.sh
